export const blogIndexPosts = [
  {
    slug: 'getting-started-with-v0',
    title: 'Getting Started with v0: A Complete Beginner\'s Guide',
    description: 'Learn how to use v0 by Vercel to generate production-ready UI components using AI.',
    publishDate: '2026-04-10',
    author: 'John Doe',
    category: 'tutorials',
    readingTime: 8,
    image: '/assets/blog/getting-started.jpg',
  },
  {
    slug: 'v0-vs-cursor-ai',
    title: 'v0 vs Cursor AI: Which is Better for UI Development?',
    description: 'An in-depth comparison of two leading AI-powered development tools.',
    publishDate: '2026-04-08',
    author: 'Jane Smith',
    category: 'reviews',
    readingTime: 12,
    image: '/assets/blog/v0-vs-cursor.jpg',
  },
  {
    slug: 'advanced-v0-techniques',
    title: '10 Advanced v0 Techniques for Power Users',
    description: 'Take your v0 skills to the next level with these pro tips and tricks.',
    publishDate: '2026-04-05',
    author: 'Alex Chen',
    category: 'guides',
    readingTime: 15,
    image: '/assets/blog/advanced-techniques.jpg',
  },
  {
    slug: 'v0-pricing-review-2026',
    title: 'Is v0 Worth It in 2026? Pricing Review',
    description: 'We analyze v0\'s pricing plans and help you choose the right one.',
    publishDate: '2026-04-01',
    author: 'Sarah Johnson',
    category: 'reviews',
    readingTime: 10,
    image: '/assets/blog/pricing-review.jpg',
  },
];
